const { isInstalled, keep } = require('./helpers')

const hasReact = isInstalled('eslint-plugin-react')
const hasA11y = isInstalled('eslint-plugin-jsx-a11y')

const reactStyleRules = {
  'react/jsx-indent': [ 'error', 2 ],
  'react/jsx-indent-props': [ 'error', 2 ],
  'react/jsx-tag-spacing': [
    'error',
    {
      afterOpening: 'never',
      beforeSelfClosing: 'always',
      closingSlash: 'never',
    },
  ],
  'react/jsx-curly-spacing': [ 'error', 'never' ],
  'react/jsx-equals-spacing': [ 'error', 'never' ],
}

const reactRules = Object.assign({
  'react/jsx-no-bind': 0,
  'react/no-did-update-set-state': 'error',
  'react/jsx-no-duplicate-props': [ 'error', { ignoreCase: true } ],
  'react/jsx-no-undef': 'error',
  'react/jsx-pascal-case': [
    'error',
    {
      allowAllCaps: true,
      ignore: [],
    },
  ],
  'react/jsx-uses-react': 'error',
  'react/jsx-uses-vars': 'error',
  'react/no-deprecated': 'error',
  'react/no-direct-mutation-state': 'error',
  'react/no-access-state-in-setstate': 'error',
  'react/no-is-mounted': 'error',
  'react/jsx-boolean-value': 'error',
  'react/no-unknown-property': 'error',
  'react/prop-types': 'error',
  'react/react-in-jsx-scope': 'error',
  'react/require-render-return': 'error',
  'react/self-closing-comp': 'error',
}, reactStyleRules)

const a11yRules = {
  'jsx-a11y/accessible-emoji': 'warn',
  'jsx-a11y/alt-text': 'warn',
  'jsx-a11y/anchor-has-content': 'warn',
  'jsx-a11y/anchor-is-valid': 'warn',
  'jsx-a11y/aria-activedescendant-has-tabindex': 'warn',
  'jsx-a11y/aria-props': 'warn',
  'jsx-a11y/aria-proptypes': 'warn',
  'jsx-a11y/aria-role': 'warn',
  'jsx-a11y/aria-unsupported-elements': 'warn',
  'jsx-a11y/click-events-have-key-events': 'warn',
  'jsx-a11y/heading-has-content': 'warn',
  'jsx-a11y/html-has-lang': 'warn',
  'jsx-a11y/iframe-has-title': 'warn',
  'jsx-a11y/img-redundant-alt': 'warn',
  'jsx-a11y/label-has-for': 'warn',
  'jsx-a11y/mouse-events-have-key-events': 'warn',
  'jsx-a11y/no-access-key': 'warn',
  'jsx-a11y/no-distracting-elements': 'warn',
  'jsx-a11y/no-onchange': 'warn',
  'jsx-a11y/no-redundant-roles': 'warn',
  'jsx-a11y/interactive-supports-focus': 'warn',
  'jsx-a11y/role-has-required-aria-props': 'warn',
  'jsx-a11y/role-supports-aria-props': 'warn',
  'jsx-a11y/scope': 'warn',
  'jsx-a11y/tabindex-no-positive': 'warn',
}

const styleRules = {
  'array-bracket-spacing': [ 'error', 'always' ],
  'arrow-parens': [ 'error', 'always' ],
  'arrow-spacing': [ 'error', { before: true, after: true } ],
  'block-spacing': [ 'error', 'always' ],
  'brace-style': [ 'error', '1tbs', { allowSingleLine: true } ],
  'comma-spacing': [ 'error', { before: false, after: true } ],
  'comma-style': [ 'warn', 'last' ],
  'dot-location': [ 'error', 'property' ],
  'func-call-spacing': [ 'error', 'never' ],
  'func-style': [ 'error', 'expression' ],
  'generator-star-spacing': [ 'error', { before: true, after: true } ],
  indent: [ 'error', 2, { SwitchCase: 1 } ],
  'jsx-quotes': [ 'error', 'prefer-double' ],
  'key-spacing': [
    'error',
    {
      beforeColon: false,
      afterColon: true,
    },
  ],
  'keyword-spacing': [ 'error', { before: true, after: true } ],
  'max-len': [
    'error',
    120,
    {
      ignoreUrls: true,
      ignoreRegExpLiterals: true,
      ignoreStrings: true,
    },
  ],
  'no-mixed-spaces-and-tabs': 'error',
  'no-tabs': 'error',
  'no-multi-spaces': [ 0 ],
  'no-multiple-empty-lines': [ 'error', { max: 1 } ],
  'object-curly-spacing': [ 'error', 'always' ],
  'object-property-newline': [ 'error', { allowMultiplePropertiesPerLine: true } ],
  'one-var': [ 0 ],
  'operator-linebreak': [
    'error',
    'after',
    {
      overrides: {
        '?': 'before',
        ':': 'before',
      },
    },
  ],
  'padded-blocks': [ 'error', 'never' ],
  quotes: [ 'error', 'single', { avoidEscape: true } ],
  'rest-spread-spacing': [ 'error', 'never' ],
  semi: [ 'error', 'never' ],
  'semi-spacing': [ 'error', { before: false, after: true } ],
  'space-before-blocks': [ 'error', 'always' ],
  'space-before-function-paren': [ 'error', 'always' ],
  'space-in-parens': [ 'error', 'never' ],
  'space-infix-ops': 'error',
  'space-unary-ops': [ 'error', { words: true, nonwords: false } ],
  'spaced-comment': [
    'error',
    'always',
    {
      line: { markers: [ '*package', '!', ',' ] },
      block: {
        balanced: true,
        markers: [ '*package', '!', ',' ],
        exceptions: [ '*' ],
      },
    },
  ],
  'template-curly-spacing': [ 'error', 'never' ],
  'yield-star-spacing': [ 'error', 'both' ],
}

const baseRules = {
  'array-callback-return': 'error',
  'arrow-body-style': [ 'error', 'as-needed' ],
  camelcase: [ 'error', { properties: 'never' } ],
  'comma-dangle': [
    'error',
    {
      arrays: 'ignore',
      objects: 'ignore',
      imports: 'ignore',
      exports: 'ignore',
      functions: 'never',
    },
  ],
  'constructor-super': 'error',
  curly: [ 'error', 'multi-line' ],
  'default-case': [ 'error', { commentPattern: '^no default$' } ],
  'eol-last': 'error',
  eqeqeq: [ 'error', 'allow-null' ],
  'guard-for-in': 'warn',
  'new-cap': [ 'error', { newIsCap: true, capIsNew: false } ],
  'new-parens': 'error',
  'no-array-constructor': 'error',
  'no-caller': 'error',
  'no-class-assign': 'error',
  'no-cond-assign': [ 'error', 'always' ],
  'no-const-assign': 'error',
  'no-constant-condition': [ 'error', { checkLoops: false } ],
  'no-control-regex': 'error',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-dupe-args': 'error',
  'no-dupe-class-members': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-duplicate-imports': 'error',
  'no-empty-character-class': 'error',
  'no-empty-pattern': 'error',
  'no-eval': 'error',
  'no-ex-assign': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-label': 'error',
  'no-extra-parens': [ 'error', 'functions' ],
  'no-fallthrough': 'error',
  'no-func-assign': 'error',
  'no-global-assign': 'error',
  'no-implied-eval': 'error',
  'no-invalid-regexp': 'error',
  'no-irregular-whitespace': 'error',
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': [ 'error', { allowLoop: false, allowSwitch: false } ],
  'no-lone-blocks': 'error',
  'no-loop-func': 'warn',
  'no-mixed-operators': [
    'error',
    {
      groups: [
        [ '&', '|', '^', '~', '<<', '>>', '>>>' ],
        [ '==', '!=', '===', '!==', '>', '>=', '<', '<=' ],
        [ '&&', '||' ],
        [ 'in', 'instanceof' ],
      ],
      allowSamePrecedence: false,
    },
  ],
  'no-multi-str': 'error',
  'no-native-reassign': 'error',
  'no-negated-in-lhs': 'error',
  'no-new-func': 'error',
  'no-new-object': 'error',
  'no-new-require': 'error',
  'no-new-symbol': 'error',
  'no-new-wrappers': 'error',
  'no-obj-calls': 'error',
  'no-octal': 'error',
  'no-octal-escape': 'error',
  'no-path-concat': 'error',
  'no-proto': 'error',
  'no-redeclare': 'error',
  'no-regex-spaces': 'error',
  'no-restricted-syntax': [ 'error', 'LabeledStatement', 'WithStatement' ],
  'no-return-assign': [ 'error', 'except-parens' ],
  'no-script-url': 'error',
  'no-self-assign': 'error',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'error',
  'no-template-curly-in-string': 'error',
  'no-this-before-super': 'error',
  'no-throw-literal': 'error',
  'no-trailing-spaces': 'error',
  'no-undef': 'error',
  'no-undef-init': 'error',
  'no-unexpected-multiline': 'error',
  'no-unneeded-ternary': [ 'warn', { defaultAssignment: false } ],
  'no-unreachable': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'no-unused-expressions': [
    'error',
    {
      allowTernary: true,
      allowShortCircuit: true,
    },
  ],
  'no-unused-labels': 'error',
  'no-unused-vars': [
    'error',
    {
      vars: 'local',
      varsIgnorePattern: '^_',
      argsIgnorePattern: '^_|...props|props',
      args: 'after-used',
      ignoreRestSiblings: true,
    },
  ],
  'no-use-before-define': [ 'error', 'nofunc' ],
  'no-useless-call': 'error',
  'no-useless-computed-key': 'error',
  'no-useless-concat': 'error',
  'no-useless-constructor': 'error',
  'no-useless-escape': 'error',
  'no-useless-rename': [
    'error',
    {
      ignoreDestructuring: false,
      ignoreImport: false,
      ignoreExport: false,
    },
  ],
  'no-var': 'error',
  'no-whitespace-before-property': 'error',
  'no-with': 'error',
  'operator-assignment': [ 'error', 'always' ],
  'quote-props': [ 'error', 'as-needed', { numbers: true } ],
  radix: 'error',
  'require-yield': 'error',
  strict: [ 'warn', 'never' ],
  'unicode-bom': [ 'error', 'never' ],
  'use-isnan': 'error',
  'valid-typeof': 'error',
  'wrap-iife': [ 'error', 'any' ],
  yoda: [ 'error', 'never' ],
  'unicorn/filename-case': [
    'error',
    {
      case: 'kebabCase',
    },
  ],
  'unicorn/no-array-instanceof': 'error',
  'unicorn/no-new-buffer': 'error',
  'unicorn/prefer-starts-ends-with': 'error',
  'unicorn/prefer-type-error': 'error',
  'linebreak-style': [ 'error', 'unix' ],
}

const rules = Object.assign(
  ...keep([
    baseRules,
    styleRules,
    hasReact && reactRules,
    hasA11y && a11yRules
  ])
)

const config = {
  parser: 'babel-eslint',
  extends: 'plugin:import/warnings',
  plugins: keep([
    hasA11y && 'jsx-a11y',
    'babel',
    hasReact && 'react',
    'unicorn'
  ]),
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    node: true
  },
  parserOptions: {
    ecmaVersion: 6,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: hasReact,
      generators: true,
      experimentalObjectRestSpread: true,
    },
  },
  rules
}

module.exports = config
